package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// fakeLLVMConfigOutputs 是假 llvm-config 对每个查询参数的 canned 输出。
var fakeLLVMConfigOutputs = map[string]string{
	"--version":     "22.1.8",
	"--includedir":  "/opt/llvm-22/include",
	"--libdir":      "/opt/llvm-22/lib",
	"--libs":        "-lLLVM-22",
	"--system-libs": "-lz -lstdc++",
}

// writeFakeLLVMConfig 在 dir 下写一个可执行的假 llvm-config shell 脚本，按参数返回 canned 输出。
func writeFakeLLVMConfig(t *testing.T, dir string, outputs map[string]string) string {
	t.Helper()
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("case \"$1\" in\n")
	for arg, out := range outputs {
		fmt.Fprintf(&b, "%s) printf '%%s\\n' %s ;;\n", arg, shQuote(out))
	}
	b.WriteString("*) echo \"unsupported: $1\" >&2; exit 1 ;;\n")
	b.WriteString("esac\n")
	path := filepath.Join(dir, "llvm-config")
	if err := os.WriteFile(path, []byte(b.String()), 0o755); err != nil {
		t.Fatalf("写入假 llvm-config 失败：%v", err)
	}
	return path
}

// shQuote 把字符串包成 shell 单引号字面量。
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// writeTempModule 在临时目录构造最小模块（go.mod + internal/binding/cgo.go），返回模块根。
func writeTempModule(t *testing.T, cgoContent string) string {
	t.Helper()
	root := t.TempDir()
	writeTempFile(t, filepath.Join(root, "go.mod"), "module "+modulePath+"\n\ngo 1.27\n")
	writeTempFile(t, filepath.Join(root, filepath.FromSlash(cgoFile)), cgoContent)
	return root
}

// writeTempFile 写入临时文件，必要时创建父目录。
func writeTempFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("创建目录失败：%v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("写入 %s 失败：%v", path, err)
	}
}

// readTempFile 读取文件内容，失败即终止测试。
func readTempFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("读取 %s 失败：%v", path, err)
	}
	return string(data)
}

// envMap 把 map 包装成 getenv 函数。
func envMap(values map[string]string) func(string) string {
	return func(key string) string { return values[key] }
}

// assertIncludeSymmetric 校验 -I"<dir>" 同时出现在 CFLAGS 与 CXXFLAGS 行：
// C++ shim 也包含 LLVM 头文件，不对称曾导致 Ubuntu CI 构建失败。
// 路径统一加引号（go/build 的 splitQuoted 支持），含空格的前缀才能落到单个 flag。
func assertIncludeSymmetric(t *testing.T, content, include string) {
	t.Helper()
	quoted := "-I\"" + include + "\""
	var inC, inCXX bool
	for _, line := range strings.Split(content, "\n") {
		switch {
		case strings.HasPrefix(line, "#cgo CFLAGS:") && strings.Contains(line, quoted):
			inC = true
		case strings.HasPrefix(line, "#cgo CXXFLAGS:") && strings.Contains(line, quoted):
			inCXX = true
		}
	}
	if !inC || !inCXX {
		t.Errorf("CFLAGS/CXXFLAGS 未对称携带 %s（CFLAGS=%v，CXXFLAGS=%v）：\n%s", quoted, inC, inCXX, content)
	}
}

// assertValidGo 断言生成内容是合法且 gofmt 稳定的 Go 源码。
func assertValidGo(t *testing.T, content string) {
	t.Helper()
	if _, err := parser.ParseFile(token.NewFileSet(), "cgo.go", content, 0); err != nil {
		t.Errorf("go/parser 解析失败：%v\n%s", err, content)
	}
	formatted, err := format.Source([]byte(content))
	if err != nil {
		t.Fatalf("生成内容不是合法 Go 源码：%v\n%s", err, content)
	}
	if string(formatted) != content {
		t.Errorf("生成内容不是 gofmt 稳定格式：\n--- got ---\n%s\n--- formatted ---\n%s", content, formatted)
	}
}

// TestRunGeneratesMachineSpecificCgo 覆盖正常生成：查询结果进入 flags、C/CXX include 对称、
// 不照抄 --cxxflags 的 -fno-exceptions，且生成结果保留 go:generate 指令。
func TestRunGeneratesMachineSpecificCgo(t *testing.T) {
	root := writeTempModule(t, "package binding\n")
	binary := writeFakeLLVMConfig(t, t.TempDir(), fakeLLVMConfigOutputs)

	var stdout bytes.Buffer
	err := run(options{
		cwd:      root,
		getenv:   envMap(map[string]string{"LLVM_CONFIG": binary}),
		lookPath: exec.LookPath,
		runCmd:   execCommand,
		stdout:   &stdout,
	})
	if err != nil {
		t.Fatalf("run 失败：%v", err)
	}

	got := readTempFile(t, filepath.Join(root, filepath.FromSlash(cgoFile)))
	for _, want := range []string{
		"// Code generated by internal/cmd/llvmconfig from " + binary + " (22.1.8); DO NOT EDIT.",
		"//go:generate go run ../cmd/llvmconfig",
		"package binding",
		"#cgo CFLAGS: -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS",
		"#cgo CXXFLAGS: -std=c++17 -fexceptions -D_GNU_SOURCE -D_GLIBCXX_USE_CXX11_ABI=1",
		"#cgo LDFLAGS: -L\"/opt/llvm-22/lib\" -lLLVM-22 -lz -lstdc++",
		"import \"C\"",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("生成内容缺少 %q：\n%s", want, got)
		}
	}
	if strings.Contains(got, "-fno-exceptions") {
		t.Errorf("不应照抄 llvm-config --cxxflags 的 -fno-exceptions：\n%s", got)
	}
	assertIncludeSymmetric(t, got, "/opt/llvm-22/include")
	assertValidGo(t, got)
	if !strings.Contains(stdout.String(), "wrote "+filepath.Join(root, filepath.FromSlash(cgoFile))) {
		t.Errorf("stdout 未报告写入路径：%s", stdout.String())
	}
}

// TestRunMissingLLVMConfig 覆盖缺失二进制：报错给出指引，且不改写 cgo.go。
func TestRunMissingLLVMConfig(t *testing.T) {
	const sentinel = "package binding\n// sentinel\n"
	root := writeTempModule(t, sentinel)
	target := filepath.Join(root, filepath.FromSlash(cgoFile))

	err := run(options{
		cwd:      root,
		getenv:   func(string) string { return "" },
		lookPath: func(string) (string, error) { return "", exec.ErrNotFound },
		runCmd: func(string, ...string) (string, error) {
			t.Fatal("找不到 llvm-config 时不应执行任何命令")
			return "", nil
		},
		stdout: io.Discard,
	})
	if err == nil {
		t.Fatal("找不到 llvm-config 时应返回错误")
	}
	for _, want := range []string{"LLVM_CONFIG", "llvm-22-dev", "CGO_CFLAGS"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("错误信息应包含 %q：%v", want, err)
		}
	}
	if got := readTempFile(t, target); got != sentinel {
		t.Errorf("报错时不应改写 cgo.go：\n%s", got)
	}
}

// TestRunCheckDoesNotWrite 覆盖 --check：报告路径/版本/目录/库，且不碰 cgo.go。
func TestRunCheckDoesNotWrite(t *testing.T) {
	const sentinel = "package binding\n// sentinel\n"
	root := writeTempModule(t, sentinel)
	target := filepath.Join(root, filepath.FromSlash(cgoFile))
	binary := writeFakeLLVMConfig(t, t.TempDir(), fakeLLVMConfigOutputs)

	var stdout bytes.Buffer
	err := run(options{
		check:    true,
		cwd:      root,
		getenv:   envMap(map[string]string{"LLVM_CONFIG": binary}),
		lookPath: exec.LookPath,
		runCmd:   execCommand,
		stdout:   &stdout,
	})
	if err != nil {
		t.Fatalf("run --check 失败：%v", err)
	}
	for _, want := range []string{
		"llvm-config: " + binary,
		"version: 22.1.8",
		"includedir: /opt/llvm-22/include",
		"libdir: /opt/llvm-22/lib",
		"libs: -lLLVM-22",
		"system-libs: -lz -lstdc++",
	} {
		if !strings.Contains(stdout.String(), want) {
			t.Errorf("--check 报告缺少 %q：\n%s", want, stdout.String())
		}
	}
	if got := readTempFile(t, target); got != sentinel {
		t.Errorf("--check 不应写文件：\n%s", got)
	}
}

// TestDiscoverLLVMConfigOrder 覆盖探测顺序与显式配置不可用时的报错。
func TestDiscoverLLVMConfigOrder(t *testing.T) {
	notFound := func(string) (string, error) { return "", exec.ErrNotFound }

	t.Run("LLVM_CONFIG 优先于 LLVM_PREFIX 与 PATH", func(t *testing.T) {
		got, err := discoverLLVMConfig(envMap(map[string]string{
			"LLVM_CONFIG": "/custom/llvm-config",
			"LLVM_PREFIX": "/prefix",
		}), func(name string) (string, error) {
			if name != "/custom/llvm-config" {
				t.Fatalf("命中 LLVM_CONFIG 后不应继续查询 %s", name)
			}
			return name, nil
		})
		if err != nil || got != "/custom/llvm-config" {
			t.Fatalf("got=%q err=%v，期望 /custom/llvm-config", got, err)
		}
	})

	t.Run("LLVM_PREFIX 拼接 bin/llvm-config", func(t *testing.T) {
		want := filepath.Join("/prefix", "bin", "llvm-config")
		got, err := discoverLLVMConfig(envMap(map[string]string{"LLVM_PREFIX": "/prefix"}),
			func(name string) (string, error) {
				if name != want {
					t.Fatalf("查询了 %s，期望 %s", name, want)
				}
				return name, nil
			})
		if err != nil || got != want {
			t.Fatalf("got=%q err=%v，期望 %q", got, err, want)
		}
	})

	t.Run("PATH 优先 llvm-config-22", func(t *testing.T) {
		var tried []string
		got, err := discoverLLVMConfig(envMap(nil), func(name string) (string, error) {
			tried = append(tried, name)
			if name == "llvm-config-22" {
				return "/usr/bin/llvm-config-22", nil
			}
			return "", exec.ErrNotFound
		})
		if err != nil || got != "/usr/bin/llvm-config-22" {
			t.Fatalf("got=%q err=%v，期望 /usr/bin/llvm-config-22", got, err)
		}
		if len(tried) != 1 {
			t.Fatalf("命中 llvm-config-22 后不应继续查询：%v", tried)
		}
	})

	t.Run("PATH 退回 llvm-config", func(t *testing.T) {
		got, err := discoverLLVMConfig(envMap(nil), func(name string) (string, error) {
			if name == "llvm-config" {
				return "/usr/bin/llvm-config", nil
			}
			return "", exec.ErrNotFound
		})
		if err != nil || got != "/usr/bin/llvm-config" {
			t.Fatalf("got=%q err=%v，期望 /usr/bin/llvm-config", got, err)
		}
	})

	t.Run("显式 LLVM_CONFIG 不可执行时直接报错", func(t *testing.T) {
		_, err := discoverLLVMConfig(envMap(map[string]string{"LLVM_CONFIG": "/missing/llvm-config"}), notFound)
		if err == nil || !strings.Contains(err.Error(), "/missing/llvm-config") {
			t.Fatalf("应报出不可执行的显式路径：%v", err)
		}
	})

	t.Run("全部缺失时报错", func(t *testing.T) {
		_, err := discoverLLVMConfig(envMap(nil), notFound)
		if err == nil || !strings.Contains(err.Error(), "找不到 llvm-config") {
			t.Fatalf("应报找不到 llvm-config：%v", err)
		}
	})
}

// TestFindModuleRoot 覆盖从嵌套目录向上定位 go.mod，以及跳过非本仓库模块。
func TestFindModuleRoot(t *testing.T) {
	root := writeTempModule(t, "package binding\n")
	nested := filepath.Join(root, "internal", "binding")
	got, err := findModuleRoot(nested)
	if err != nil {
		t.Fatalf("findModuleRoot 失败：%v", err)
	}
	if got != root {
		t.Fatalf("got=%q，期望模块根 %q", got, root)
	}

	t.Run("跳过非本仓库 go.mod", func(t *testing.T) {
		other := t.TempDir()
		writeTempFile(t, filepath.Join(other, "go.mod"), "module example.com/other\n")
		if _, err := findModuleRoot(other); err == nil {
			t.Fatal("非本仓库 module 时应报错")
		}
	})
}

// TestLinkFlagsOmitsEmptySystemLibs 覆盖 --system-libs 为空时不留多余空格。
func TestLinkFlagsOmitsEmptySystemLibs(t *testing.T) {
	cfg := llvmConfig{libDir: "/usr/lib", libs: "-lLLVM-22"}
	if got := linkFlags(cfg); got != "-L\"/usr/lib\" -lLLVM-22" {
		t.Errorf("got=%q，期望 %q", got, "-L\"/usr/lib\" -lLLVM-22")
	}
}

// TestRunGeneratesCgoWithSpacePrefix 覆盖含空格的非标准前缀：include/lib 路径必须
// 加引号才能通过 go/build 的 splitQuoted 落到单个 flag，否则生成文件不可编译。
func TestRunGeneratesCgoWithSpacePrefix(t *testing.T) {
	const (
		includeDir = "/opt/llvm 22/include"
		libDir     = "/opt/llvm 22/lib"
	)
	outputs := map[string]string{
		"--version":     "22.1.8",
		"--includedir":  includeDir,
		"--libdir":      libDir,
		"--libs":        "-lLLVM-22",
		"--system-libs": "",
	}
	root := writeTempModule(t, "package binding\n")
	binary := writeFakeLLVMConfig(t, t.TempDir(), outputs)

	if err := run(options{
		cwd:      root,
		getenv:   envMap(map[string]string{"LLVM_CONFIG": binary}),
		lookPath: exec.LookPath,
		runCmd:   execCommand,
		stdout:   io.Discard,
	}); err != nil {
		t.Fatalf("run 失败：%v", err)
	}

	got := readTempFile(t, filepath.Join(root, filepath.FromSlash(cgoFile)))
	for _, want := range []string{
		"#cgo CFLAGS: -I\"" + includeDir + "\"",
		"#cgo CXXFLAGS: -I\"" + includeDir + "\"",
		"#cgo LDFLAGS: -L\"" + libDir + "\" -lLLVM-22",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("含空格路径未按引号包裹：缺少 %q：\n%s", want, got)
		}
	}
	assertIncludeSymmetric(t, got, includeDir)
	assertValidGo(t, got)
}

// TestQueryLLVMConfigErrors 覆盖查询阶段的错误分支：路径为空、libs 为空、命令执行失败。
func TestQueryLLVMConfigErrors(t *testing.T) {
	base := map[string]string{
		"--version":     "22.1.8",
		"--includedir":  "/opt/llvm-22/include",
		"--libdir":      "/opt/llvm-22/lib",
		"--libs":        "-lLLVM-22",
		"--system-libs": "-lz",
	}
	// override 基于 base 复制并覆盖指定参数，保证各子用例只偏离一个维度。
	override := func(key, value string) map[string]string {
		out := make(map[string]string, len(base))
		for k, v := range base {
			out[k] = v
		}
		out[key] = value
		return out
	}

	cases := []struct {
		name    string
		outputs map[string]string
		failArg string
		wantErr string
	}{
		{"includedir 为空", override("--includedir", ""), "", "未返回 includedir"},
		{"libdir 为空", override("--libdir", ""), "", "未返回 libdir"},
		{"libs 为空", override("--libs", ""), "", "--libs 为空"},
		{"命令执行失败", base, "--libdir", "fake-llvm-config --libdir: exit status 1"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			runCmd := func(_ string, args ...string) (string, error) {
				arg := args[0]
				if arg == tc.failArg {
					return "", errors.New("exit status 1")
				}
				out, ok := tc.outputs[arg]
				if !ok {
					return "", fmt.Errorf("unsupported arg: %s", arg)
				}
				return out, nil
			}
			_, err := queryLLVMConfig(runCmd, "fake-llvm-config")
			if err == nil {
				t.Fatal("应返回错误")
			}
			if !strings.Contains(err.Error(), tc.wantErr) {
				t.Errorf("错误信息应包含 %q：%v", tc.wantErr, err)
			}
		})
	}
}
