package binding

// Automatically generated by `make config`, do not edit.

// #cgo CFLAGS: -I${SRCDIR}/include  -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
// #cgo CXXFLAGS: -I${SRCDIR}/include -std=c++17 -stdlib=libc++  -fno-exceptions -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
// #cgo LDFLAGS: -lLLVM-17
import "C"
